services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: studypath_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: studypath
      POSTGRES_PASSWORD: studypath123
      POSTGRES_DB: studypath_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U studypath -d studypath_db']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
